* LaTeX
** Qué es LaTeX ?

   LaTex es un softaware de composición de documentos, en otras
   palabras es un sistema de preparación de documentos.
   Latex no es un procesador de texto, pero es usado lenguaje de
   marcado de documentos.

** Licencia

   LaTeX es libre, es software open source. LaTeX fue originalmente
   escrito por leslie lamport y es basado en TeX, el composicitor de
   documentos de Donald Knuth.

** Beneficio

   LaTeX esta especialmente provisto para documentos cientificos y
   tecnicos.
   La superior composición tipografica para formulas matematicas es
   legendaria.

   Otra notable fortaleza de LaTex son sus niveles de referencia
   cruzada, su numeración automatica y  generación de listas de
   contenido, figuras, tablas, indices, glosarios y bibliografía.

   Gracias a la flexibilidad existe una gran cantidad de templates
   para cartas, presentaciones, partituras, y notaciones para juegos.

   Otros de los beneficios son su impresionante alta calidad de sus
   estilos    predefinidos apoyandose en su inteligente formateo del
   texto, pero permite al usuario libre libertad de modificación.

** Separación de la forma y el contenido.

   Uno de los principios LaTeX, no debe distraerse demasiado por
   formatear el documentos. Normalmente, el autor se enfoca en el
   contenido y el formato un ejemplo, en vez de escribir el title de
   un capitulo en grande y negrita, solo tienes que decirle LaTeX que
   es la cabesera de una sección.
   La ventaja es que puedes permitir que LaTeX decida el diseño para
   la cabezera o puedes definir como debera de mostrarse y todo puede
   ser definido una vez y aplicarse a todo el documento.

   LaTeX archivos que permitan extender el estilo del documento, a
   estos se les da el nombre de clases y paquetes, y proveen una
   forma mas sencillas de modificar o diseñar la aparencia de todo el
   documento o algunas partes.

** Portabilidad
   LaTeX esta disponible para casi todos los sistemas opertivos, como
   son Linux, Mac OS X, Windows y otros mas. El formato del archivo es
   texto plano, el cual puede ser leido y editado en todos los
   sistemas operativos. LaTeX debera de generar la misma salida en
   todos los sistemas, Aunque existen diferents paquetes de software,
   que son llamados Districuciones TeX.

   LaTeX no tiene una interfaz grafica, esta es una de las razones por
   las que LaTeX es muy portable.

   LaTeX puede genera un PDF, esto es que puede ser leido e impreso en
   muchas computadoras, adicionalmente genera salida en los formatos
   DVI, PostScript y html.

   Tomando en cuanta todo esto podemos decir que LaTex es portable en
   tres maneras, la fuente, la implementación y la salida.

** Inicio en LaTeX
*** EL primer paso

    El primer programa siempre es importante.

**** Código

    Empezemos por un ya clasico hola mundo en LaTeX

    #+BEGIN_SRC latex
    % Hola mundo en LaTeX
    \documentclass[a4paper, 13pt]{article}

    \begin{document}
    \title{Hola mundo}
    \author{Miguel Angel Gordi\'an}
    \date{Marzo 23, 2012}
    \maketitle

    \section{saluda}
    Hola mundo en \LaTeX

    \end{document}
    #+END_SRC

**** Compilación

     pdflatex mas el nombre del archivo para dar una salidad a pdf.

    #+BEGIN_SRC bash
      $ pdflatex holamundo.tex
    #+END_SRC

     latex para generar una salida a dvi.

    #+BEGIN_SRC bash
      $ latex holamundo.tex
    #+END_SRC

*** Que ha pasado
    Anteriormente habiamos hablado hacerca de un formateo logico.
    Tomando el codigo anterior nostros le decimos a LaTeX que:

    * Nuestro documentos es de tipo articulo. Este debera ser
      impreso en un tamaño de papel A4 usando un tamaño de letra
      de 11 puntos.

    * El titulo es Hola mundo

    * El nombre del autor.

    * La fecha en que el documento fue escrito.

    * Concerniente al contenido del documento:
      - Inicia con un titulo

      - La primera seccion debera tener la cabecera "Saludame"

      - El texto "hola mundo desde \LaTeX".

    Nota: En el archivo no se especifico el tamaño de letra del titulo
    o la cabezera de la sección, ni se especifico algo con formato en
    negrita o centrado. El formateo fue hecho por LaTeX sin embargo
    eres libre de decirle a LaTeX como debera de lucir el documento.

*** Disección el hola mundo
    Un documento en LaTeX no es independiente, nomalmente el documento
    es basado en un versatil template.
    Un template fundamental es llamado una clase, este proveé de
    caracteristicas personalizables y usualmente es creado para un
    proposito en especifico. Existen clases para libros, articulos de
    periodico, cartas, presentaciones, posters, y muchos mas.
    Cientos de clases pueden ser encontrados en los archivos de
    internet, pero tambien algunos ya estan en tu computadora si ya
    instalaste Tex Live. En el codigo enterior nosotros escojimos la
    clase article, una clase estandard en LaTeX adecuada para pequeños
    documentos.

    La primera linea del codigo inicia con \documentclass. Esta
    palabra inicia con diagonal invertida, tales palabras son
    llamadas comando.
    Los comandos se utilizan para especificar la clase o el estado de
    algunas propiedades del documento:

    * \title: Especifica el titulo del documento

    * \author: Especifica el nombre del autor

    * \date: Especifica la fecha para la creacion del documento.

    La primera parte del documento es llamado preambulo(preamble) del
    documento. En el preambulo es donde escojemos la clase,
    especificamos algunas propiedades.

    El comando \begin{document} marca el final del preambulo y el
    inicio del documento. \end{document} marca el final del documento.
    Todo lo que exista despues del comando, debera de ser ignorado por
    LaTeX.

    El par de comandos \begin y \end forman un marco al cual se les da
    el nombre de ambiente(environment).

    En el codigo anterior, se uso el comando \maketitle que imprime el
    titulo, autor y fecha con un formato correcto. En el caso del
    comando \section, produjo un texto mas grande y en negrita que el
    texto normal.
    En el environment del documento se escribio un saludo, este debera
    se ser impreso, al contrario del preambulo que nunca producira
    alguna salida.

*** Comandos

    Los comando en LaTeX comienzan con una diagonal inversa, seguidos
    por letras mayusculas o minusculas.
    Los comando en LaTeX usualmente son nombrados con letras en
    minuscula y un nombre descriptivo. Tambien ha excepciones, algunos
    de los comandos consisten de la diagonal inversa y un caracter
    especial.

    Los comandos pueden tener argumentos, estos le son pasados
    mediante corchetes o llaves.

    LLamar a un comando puede lucir:

    \command

    ó:

    \command{argument}

    ó:

    \command[argumentos opcionales]{argumento}

    Cada uno puede contener varios argumentos, los argumentos en
    llaves son obligatorios. Si un comando es definido para recivir un
    argumento, uno tiene que ser provisto. Un ejemplo, al llamar al
    comando \documentclass debera de fallar si no se especifica el
    nombre de una clase valida.

    Existe una gran variedad de comando, algunos generan salida como
    \LaTeX, otros cambian la tipografia o las etiquetas, generalmente
    los nombres de los comandos son acorde a su proposito.

*** LaTeX te entiende

    Latex entiende lo que has escrito en el editor, modifiquemos un
    poco el ejemplo anterior.

    #+BEGIN_SRC latex
    % Hola mundo en LaTeX
    \documentclass[a4paper, 13pt]{article}

    \begin{document}
    \title{Hola mundo, parte 2}
    \author{Miguel Angel Gordi\'an}

    \date{Marzo 23, 2012}
    \maketitle

    \section{¿Qu\'e es esto?}
    Hola mundo en \LaTeX

    Este
    es
    nuestro
    Segundo Documento


    Contiene dos parrafos. La primera line de un parrafo debera
    de ser indetada, pero no sera indentada cuando se encuentre
    despues de una cabecera.
    % Fin del parrafo
    \end{document}
    #+END_SRC

**** ¿Qué paso?

     Aunque se insertaron espacios de mas, la distancia entre las
     palabras en el documento se salida se mantienen igual.
     La explicación de este fenomeno es que LaTeX trata multiples
     espacios como si fuera uno solo.
     Los saltos de linea tienen el mismo efecto y son tratados
     como un solo espacio

     Otro fenomeno de la misma naturalesa es que una linea en blanco
     denota el fin de un parrafo. Como los espacios, multiples lineas
     en blanco son tratados como si fueran una.

     Resumiendo, los espacios separan palabras, las lineas en blanco
     separan parrafos.

**** El carácter %

     Como has podido notar desde el primer ejemplo, hay una linea que
     comentado anteriormente todo lo que existe en el preámbulo no
     genera salida al documento pero y en el segundo ejemplo aparece
     otro similar pero esta vez dentro del environment(ambiente)
     document, pero no genero contiene el símbolo de %, seguido de
     texto pero como ya hemos alguna salida. ¿Qué significa esto?

     La respuesta a esta interrogante es que el signo de porcentaje
     marca el inicio de un comentario, todo lo que siga despues del
     signo de porcentaje hasta el salto de linea sera tomado como
     comentario y no generara alguna salida. Los comentarios son
     ignorados por LaTeX y esto posibilita mantener  notas en el
     documento.

     Los comentarios son comúnmente utilizados en templates para
     indicarle al usuario lo que realiza el template en ciertos
     lugares.
     Algo a notar es que el fin de linea, que normalmente se comporta
     como espacio, debera ser ignorado despues del signo de
     porcentaje.

     Si el signo de porcentaje se utiliza para indicar un comentario,
     ¿Que pasa si queremos escribir cifras en formato de porcentaje?

*** Caracteres especiales.

    Los textos comúnmente contienen letras en mayúscula, minúsculas,
    números, signos de puntuación y tu puedes tener lo mismo en Látex
    simplemente escribiéndolo cuando estés en el editor. Sin embargo
    algunos caracteres están reservados para los comandos en LaTeX, lo
    que significa es que no pueden llegar a ser usados directamente.

    Ya se han usado caracteres que son comandos de LaTeX, como el
    signo de porcentaje y las llaves, pero si se quiere escribir estos
    caracteres en el documento LaTeX no te deja morir solo si no que
    te provee de comandos para imprimir este tipo de caracteres.

**** Código
    #+BEGIN_SRC latex
     \documentclass{article}
     \begin{document}
     Decalraci\'on \#1:
     50\% de 100\% es \$50.

     Otros caracteres especiales son \&, \_, \{ y \}.

     \end{document}
    #+END_SRC

**** Devuelta a la disección
     La solución que nos ofrece LaTeX, es colocar una
     diagonal inversa antes del símbolo especial,
     convirtiendo el carácter especial en un comando
     cuyo único propósito es imprimir ese símbolo.

     Un caso curioso es el de la diagonal inversa,
     con la explicación anterior se pensaría que para
     mostrar la diagonal se haría mediante el comando
     "\\", pero no es así, se hace mediante el comando
     \textbackslash. La labor del comando "\\" es
     frecuentemente utilizada como un atajo que indica
     un salto de linea.
     Es un poco extraño, que los saltos de linea ocurren
     frecuentemente mientras que las diagonales inversas
     son raramente usadas en el documento generado, de ahí
     que se escogiera este atajo.

     Existe una gran variedad de símbolos que podemos usar
     para formulas matemáticas, notación de ajedrez, signos
     zodiacales, y mas. Pero por lo retomaremos mas tarde.

*** Formateando al texto
    LaTeX le da formato de manera automática a algunas partes del texto, por
    ejemplo, hasta el momento hemos visto que las cabecera de la sección son
    mas grande el texto normal y en negrita. A continuación aprenderemos como
    modificar la apariencia del texto a nuestro gusto.

**** Estilo
***** Código
     A continuación enfatizaremos un palabra importante en el texto y veremos
     como hacer que las palabras se muestren en negrita, itálica o cursiva.
     #+BEGIN_SRC latex
     \documentclass{article}
     \begin{document}
     El texto puede ser \emph{enfatizado}.

     Tambi\'en puede ser \textit{ita\'alica}, \textbf{negrita},
     \textsl{inclinada}, o en \textsc{Versal}.

     Los comando pueden estar \textit{\textbf{anidados}}.

     \emph{Veamos como luce un \emph{\'enfasis} anidado.}
     \end{document}
     #+END_SRC

***** Disección
     En primera instancia podemos observar que el primer comando es el
     de \emph, pasándole como argumento una palabra. El argumento
     deberá ser mostrado en itálica, debido a que esta es la forma
     predefinida en la que LaTeX enfatiza el texto.


     Los comandos para formatear el texto normalmente mantienen la
     forma \text**{argumento}, donde **, son dos letras las cuales son
     la abreviación del formato.  La abreviación para la negrita, bold
     en ingles es bf, para la itálica es it, para la inclinada sl. El
     argumento deberá de ser formateado acorde a lo que hemos visto.

     También se anido el comando \textbf en \textit, lo cual nos
     permitió lograr la combinación de los dos estilos, dando así un
     texto compuesto por negrita e itálica.

     La mayoría de los comandos deberán mostrarse de la misma manera
     si es aplicado una segunda vez dentro del mismo, es decir,
     \textbf{\textbf{Algo}} la palabra Algo no sera mas negrita. La
     única excepción es \emph, la cual deberá de cambiar de itálica al
     estilo normal.  Poniendo un ejemplo para dar una imagen del por
     que de este comportamiento, supongamos que tenemos teorema muy
     importante compuesto por puras itálicas, aun tendremos la
     posibilidad de resaltar palabras dentro del teorema.

     Un dato importante es que \emph también es llamado marcado
     semántico puesto que hace referencia a el significado, no solo a
     la apariencia

**** Fuentes
     Imaginemos que queremos escribir un articulo acerca de donde
     podemos obtener recursos para LaTeX en internet. Para tener un
     titulo o una cabecera legible debemos de usar una fuente sin
     elementos decorativos, el cuerpo del texto deberá de contener una
     dirección de internet, para hacer hincapié en el link usaremos
     una fuente del tipo de las maquinas de escribir.


***** Código
    #+BEGIN_SRC latex
      \documentclass{article}
      \begin{document}
      \section{\textsf{Recursos de \LaTeX\ en internet}}
      El mejor lugar para descargar software relacionado con LaTeX es CTAN.
      Su dirección es \texttt{http://www.ctan.org}.
      \end{document}
    #+END_SRC
***** Disección
      En el código anterior se han escrito mas comandos de fuentes. Al
      colocar el comando \textsf, le hemos dicho a LaTeX que use la
      fuente sans-serif para la cabecera de la sección. También se ha
      escrito el comando \texttt para usar una fuente similiar a la de
      las maquinas de escribir aplicada a la direción
      electronica. Ambos comandos pueden ser usados como los
      anteriores comandos de fuente.

      Las letras que forman parte del standard de LaTeX son llamadas
      serif, y presentan pequeños detalles decorativos al final de los
      trazos de una letra.  Serif deberá mejorar la legibilidad y
      guiar a los ojos del usuario a lo largo de linea. Por lo tanto
      es muy usada en el cuerpo del documento. Tales fuentes son
      también llamadas fuentes Roman, la cual tiene asociado el
      comando \textrm — la fuente predefinida con serifs.

      Las cabeceras de sección son frecuentemente hechas sin serifs,
      en ves de ella utilizan una fuente llamada sans-serif. Esta
      fuente también es una excelente elección para texto mostrado en
      una pantalla debido a que provee una mejor legibilidad en poca
      resolución.  Tal vez quieras elegir una fuente sans-serif cuando
      escribas un e-book.

      Si cada letra de una fuente tiene el mismo ancho, la fuente es
      llamada monoespaciada o typewriter.  La fuente typewriter fue
      usada en los inicios de la computadora, hoy en día aun son
      utilizadas principalmente para escribir código de programas de
      computadora, tanto cuando se imprimen como cuando se esta en un
      editor de texto.  En el caso de mostrar codigo de programas o de
      LaTeX, considera usar una fuente typewriter.

**** Intercambiando fuentes
     Colocar demasiado texto dentro del argumento de un comando puede
     ser grotesco y puede que algunas veces queramos establecer
     algunas propiedades de la fuente para largos pasajes de
     texto. Así que LaTeX provee mas comandos, pero estos tendrán la
     labor de actuar como switchs.

***** Código

    #+BEGIN_SRC latex
      \documentclass{article}
      \begin{document}
      \section{\sffamily Recursos de \LaTeX\ en internet}
      El mejor lugar para descargar software relacionado con LaTeX es CTAN.
      Su dirección es \ttfamlily http://www.ctan.org\rmfamily\rmfamily.
      \end{document}
    #+END_SRC

***** Disección
      Al colocar el comando \sffamily, le decimos a LaTeX que cambia a
      la fuente sans-serif, este cambio fue hecho dentro del
      argumento, y solo es valido ahí.

      También se uso el comando \ttfamily para cambiar a la fuente
      typewriter, la fuente deberá de ser usada hasta justo antes del
      punto, puesto que volvemos a cambiar de fuente, en este caso
      regresamos a la fuente Roman mediante el comando \rmfamily.

      Este tipo de comandos no causan alguna salida, pero afectaran al
      texto que lo prosigue. Llamaremos a este tipo de comandos
      declaraciones.

      Veamos con mayor detalle el numero de la sección, este en un
      dígito con serif, el cual no guarda relación con el resto de la
      cabecera que es sans-serif. Por otra parte, cambiar la fuente
      dentro del comando sección no luce bien. La mejor manera es
      declarar una vez la fuente para las cabecera de sección y que se
      aplique para todo el documento.

**** Sumario de los comandos y las declaraciones.
     | Comando          | Declaración | Significado       |
     |------------------+-------------+-------------------|
     | \textrm{...}     | \rmfamily   | roman family      |
     | \textsf{...}     | \sffamily   | sans-serif family |
     | \texttt{...}     | \ttfamily   | typewriter family |
     | \textbf{...}     | \bfseries   | bold face         |
     | \textmd{...}     | \mdseries   | medium            |
     | \textit{...}     | \itshape    | italic shape      |
     | \textsl{...}     | \slshape    | slanted shape     |
     | \textsc{...}     | \scshape    | Small Caps Shape  |
     | \textup{...}     | \upshape    | uprigth shape     |
     | \textnormal{...} | \normalfont | default font      |


     La declaración correspondiente a \emph es \em

*** Delimitando el efecto de los comandos
    En el capitulo anterior, se revirtio el efecto de \ttfamily para
    escribir el punto con el tipo de letra predefinido para el texto
    comun mediante el comando \rmfamily. Pudimos haber asegurado
    regresar al tipo de letra base mediante el comando \normalfont,
    sin embargo existe una forma mas sencilla.

**** Código
     Es tiempo de pasar nuevamente al código, esta vez utilizaremos
     las llaves para decirle a LaTeX, donde comenzar a aplicar un
     comando y donde detenerse.

#+BEGIN_SRC latex
     \document{article}
     \begin{document}
     {sffamily
     El texto puede ser {\em enfatizado}.

     Además pueden estar en {\itshape itálica} o también ser
     {\bfserief negritas}, {\slshape inclinada} o compuesta en
     {\scshape versalita}.

     Tales comandos puedes estar {\itshape \bfseries anidados}.}

     Por ultimo {\em Observa como se muestra el {\em enfatizado}
     cuando esta anidado}
     \end{document}
#+END_SRC

**** Disección
     Cuando colocamos el símbolo de llave abierta, el siguiente
     comando \sffamily solo tendrá efecto en el texto hasta el
     correspondiente cierre de llave. Se puede observar que la llave
     que cierra se encuentra al final del código resaltado. El texto
     resaltado muestra el área de código donde el comando \sffamily es
     valido.

     En el código anterior se remplazo cada comando por su correspondiente
     declaración. Si recordemos, \em es la declaración del comando \emph.
     Adicionalmente encerramos cada declaración y el texto afectado mediante
     llaves.

     Para una mayor comprensión, cuando colocamos la llave abierta le
     decimos a LaTeX que iniciamos un *grupo*[fn:1]. Los comandos siguientes
     a la llave son validos, es decir tendrán efecto sobre el
     siguiente texto hasta que se encuentre con la llave que cierra,
     haciendo que LaTeX detenga el efecto de los comandos contenidos
     en el grupo.  El rango donde un comando tiene efecto es conocido
     como *scope*(alcance).

     Un elemento importante es que los grupos pueden estar anidados.

     Texto Normal, {\sffamily texto sans serif {\bfseries y negrita}}.

     Se debe ser cuidadoso al momento de cerrar los grupos, ya que
     debe de concordar.

*** Tamaños de fuente
    En este apartado mostraremos los comandos de tamaño de texto  disponible
    en LaTeX por defecto.

**** Código
#+BEGIN_SRC latex
\documentclass{article}
\begin{document}
    \noindent\tiny ¡Hemos \scriptsize de iniciar \footsize \small de
    lo pequeño, \normalize hasta \large agrandarse \Larger y
    agrandarse mas, \huge hasta lo Enorme y \Huge giganteco!
\end{document}
#+END_SRC

**** Disección
     indentación del parrafo. Después de ello, utilizamos las 10 declaraciones de
     tamaño, comenzando desdes la mas pequeña \tiny y terminando con las mas grande
     En primera instancia, se uso el comando \noindent. Este comando suprime la
     \Huge. Estos comando no toman argumentos, por lo tanto hay que usar llaves
     para delimitar su efecto, como se hablo antes.

     El actual resultado del tamaño de la fuente depende de la fuente base. Esto
     es que si en tu documento tienes una fuente base de 12pt, entonces \tiny
     deberá de ser el texto mas grande que si la fuente fuese de 10pt.

     Debemos de ver algunas relaciones, si usas \footsize, obtendrás texto del
     mismo tamaño del que LaTeX utiliza para las notas al pie. Otra relación es
     la de usar \scriptsize, si se desea crear un estilo, con el mismo tamaño
     de letra que usa LaTeX para los subscripts y superscripts.

     Normalmente, las declaraciones del texto son usadas únicamente en declaraciones
     de macros en el preámbulo, justo como se aplica a los demás comandos de fuente.
     Sera muy raro que encuentres comandos de tamaño o de estilo en cuerpos de texto
     bien hechos, excepto pasajes de diseño libres como titulo de paginas.

*** El uso de ambientes
    Cuando se usan demasiadas declaraciones y se agrupan mediante llaves para
    delimitar su contenido, se tienden a cometer el error de no cerrar las
    llaves correspondientes. En esos casos es cuando llega el auxilio de los
    ambientes(environmets), los cuales forman también grupos, pero genera una
    mayor legibilidad en el código.

**** Código
   #+BEGIN_SRC latex
\documentclass{article}
\begin{document}
    \begin{huge}
         \bfseries
         Un pequeño ejemplo
    \end{huge}
    \bigskip
    Esto es otro pequeño ejemplo.
\end{document}
   #+END_SRC

**** Disección
     Veamos que en vez de colocar el comando \huge, escribimos \begin{huge},
     ambos tienen el mismo efecto de cambiar a un tamaño de letra grande.
     Tambien se escribio \end{huge}, el cual le informa a LaTeX que debera
     dejar de aplicar el efecto. Desde este punto en adelante, el texto tendra
     el mismo tamaño que tenia antes de \begin{huge}.

     Dentro del ambiente, usamos la declracion \bfseries. Notese que el efecto
     de esta declaración termina junto con la del ambiente.

     La linea en blanco antes de el \end{huge} denota el fin de un parrafo. [fn:2]
     \bigskip, Usando este comando evitamos que se genere algun espacio vertical.

     *Importante:* Para cada declaración, existe su ambiente corespondiente, el
     cual lleva el mismo nombre solo se excluye la diagonl inversa.

     Usando ambientes en vez de llavez puede hacer de un codigo complejo uno
     mas legible y entendible.




...

[fn:1] Las llaves que encierran a los argumentos de un comando, no
forman un grupo.

[fn:2] Habras notado que la linea blanca que denota el fin de parrafo se
encuentra antes de que la fuente cambia de tamaño y no despues, esto es debido
a que LaTeX calcula el espacio para interlineado dependiendo del tamaño actual
de la fuente.
