* LaTeX
** Qué es LaTeX ?
   LaTex es un softaware de composición de documentos, en otras palabras
   es un sistema de preparación de documentos.
   Latex no es un procesador de texto, pero es usado lenguaje de marcado
   de documentos.

** Licencia
   LaTeX es libre, es software open source. LaTeX fue originalmente
   escrito por leslie lamport y es basado en TeX, el composicitor de 
   documentos de Donald Knuth.

** Beneficio
   LaTeX esta especialmente provisto para documentos cientificos y tecnicos.
   La superior composición tipografica para formulas matematicas es 
   legendaria.
   
   Otra notable fortaleza de LaTex son sus niveles de referencia cruzada, su
   numeración automatica y  generación de listas de contenido, figuras,
   tablas, indices, glosarios y bibliografía.

   Gracias a la flexibilidad existe una gran cantidad de templates para cartas, 
   presentaciones, partituras, y notaciones para juegos. 

   Otros de los beneficios son su impresionante alta calidad de sus estilos 
   predefinidos apoyandose en su inteligente formateo del texto, pero permite
   al usuario libre libertad de modificación.

** Separación de la forma y el contenido.
   Uno de los principios LaTeX, no debe distraerse demasiado por formatear el 
   documentos. Normalmente, el autor se enfoca en el contenido y el formato
   un ejemplo, en vez de escribir el title de un capitulo en grande y negrita,
   solo tienes que decirle LaTeX que es la cabesera de una sección.
   La ventaja es que puedes permitir que LaTeX decida el diseño para la 
   cabezera o puedes definir como debera de mostrarse y todo puede ser definido
   una vez y aplicarse a todo el documento.

   LaTeX archivos que permitan extender el estilo del documento, a estos se les
   da el nombre de clases y paquetes, y proveen una forma mas sencillas de
   modificar o diseñar la aparencia de todo el documento o algunas partes.

** Portabilidad
   LaTeX esta disponible para casi todos los sistemas opertivos, como son Linux,
   Mac OS X, Windows y otros mas. El formato del archivo es texto plano, el cual
   puede ser leido y editado en todos los sistemas operativos. LaTeX debera de
   generar la misma salida en todos los sistemas, Aunque existen diferents 
   paquetes de software, que son llamados Districuciones TeX.

   LaTeX no tiene una interfaz grafica , esta es una de las razones por las que 
   LaTeX es muy portable. 

   LaTeX puede genera un PDF, esto es que puede ser leido e impreso en muchas
   computadoras, adicionalmente genera salida en los formatos DVI, PostScript y 
   html.

   Tomando en cuanta todo esto podemos decir que LaTex es portable en tres
   maneras, la fuente, la implementación y la salida.

      
** Inicio en LaTeX
*** EL primer paso
    El primer programa siempre es importante.

**** Codigo
    Empezemos por un ya clasico hola mundo en LaTeX

    % Hola mundo en LaTeX
    \documentclass[a4paper, 13pt]{article}
    
    \begin{document}
    \title{Hola mundo}
    \author{Miguel Angel Gordi\'an}
    \date{Marzo 23, 2012}
    \maketitle
    
    \section{saluda}
    Hola mundo en \LaTeX
    
    \end{document}

**** Compilación
     pdflatex mas el nombre del archivo para dar una salidad a pdf.

      $ pdflatex holamundo.tex

     latex para generar una salida a dvi.

      $ latex holamundo.tex
    

*** Que ha pasado
    Anteriormente habiamos hablado hacerca de un formateo logico.
    Tomando el codigo anterior nostros le decimos a LaTeX que:

    * Nuestro documentos es de tipo articulo. Este debera ser
      impreso en un tamaño de papel A4 usando un tamaño de letra 
      de 11 puntos.

    * El titulo es Hola mundo

    * El nombre del autor.

    * La fecha en que el documento fue escrito.

    * Concerniente al contenido del documento:
      - Inicia con un titulo
      
      - La primera seccion debera tener la cabecera "Saludame"

      - El texto "hola mundo desde \LaTeX".

    Nota: En el archivo no se especifico el tamaño de letra del titulo 
    o la cabezera, ni se especifico algo con formato en negrita o 
    centrado. El formateo fue hecho por LaTeX sin embargo eres libre
    de decirle a LaTeX como debera de lucir el documento.
    
*** Disección el hola mundo
    Un documento en LaTeX no es independiente, nomalmente el documento
    es basado en un versatil template.
    Un template fundamental es llamado una clase, este proveé de
    caracteristicas personalizables y usualmente es creado para un 
    proposito en especifico. Existen clases para libros, articulos de 
    periodico, cartas, presentaciones, posters, y muchos mas.
    Cientos de clases pueden ser encontrados en los archivos de 
    internet, pero tambien algunos ya estan en tu computadora si ya
    instalaste Tex Live. En el codigo enterior nosotros escojimos la 
    clase article, una clase estandard en LaTeX adecuada para pequeños
    documentos.

    La primera linea del codigo inicia con \documentclass. Esta palabra
    inicia con diagonal invertida, tales palabras son llamadas comando.
    Los comandos se utilizan para especificar la clase o el estado de 
    algunas propiedades del documento: 
    
    * \title: Especifica el titulo del documento
      
    * \author: Especifica el nombre del autor
      
    * \date: Especifica la fecha para la creacion del documento.

    La primera parte del documento es llamado preambulo(preamble) del 
    documento. En el preambulo es donde escojemos la clase,
    especificamos algunas propiedades.

    El comando \begin{document} marca el final del preambulo y el inicio del 
    documento. \end{document} marca el final del documento. Todo lo que 
    exista despues del comando, debera de ser ignorado por LaTeX. 

    El par de comandos \begin y \end forman un marco al cual se les da el 
    nombre de ambiente(environment).

    En el codigo anterior, se uso el comando \maketitle que imprime el titulo,
    autor y fecha con un formato correcto. En el caso del comando \section,
    produjo un texto mas grande y en negrita que el texto normal.
    En el environment del documento se escribio un saludo, este debera se ser
    impreso, al contrario del preambulo que nunca producira alguna salida.
    
*** Comandos
    Los comando en LaTeX comienzan con una diagonal inversa, seguidos 
    por letras mayusculas o minusculas. 
    Los comando en LaTeX usualmente son nombrados con letras en minuscula
    y un nombre descriptivo. Tambien ha excepciones, algunos de los 
    comandos consisten de la diagonal inversa y un caracter especial.

    Los comandos pueden tener argumentos, estos le son pasados mediante
    corchetes o llaves.

    LLamar a un comando puede lucir:

    \command

    ó:
    
    \command{argument}

    ó:

    \command[argumentos opcionales]{argumento}

    Cada uno puede contener varios argumentos, los argumentos en llaves son
    obligatorios. Si un comando es definido para recivir un argumento, uno
    tiene que ser provisto. Un ejemplo, al llamar al comando \documentclass 
    debera de fallar si no se especifica el nombre de una clase valida.

    Existe una gran variedad de comando, algunos generan salida como \LaTeX,
    otros cambian la tipografia o las etiquetas, generalmente los nombres de
    los comandos son acorde a su proposito.
